### ISSUE TITLE
Cannot install using vagrant plugin install

### ISSUE THREAD

**Issue by Loksly** [kusnier/vagrant-persistent-storage#54]
Hello everyone,

I can't install this plugin using:
`vagrant plugin install vagrant-persistent-storage`

```
Installing the 'vagrant-persistent-storage' plugin. This can take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:102:in `install'
from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:62:in `block in install_plugin'
from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:72:in `install_plugin'
from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:37:in `call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:32:in `block in execute'
from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `each'
from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `execute'
from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
from /usr/bin/vagrant:173:in `<main>'
```

I'm using: 
- Ubuntu 16.04.1 LTS
- Vagrant 1.8.1
- VirtualBox 5.0.24_Ubuntu r108355
- Ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

The line is almost this one (the apt-get version is not exactly the same one as the last one on github)
https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb#L950

If this is not something that happens to more people let me know, then I can try some other configurations.

have a nice day.

**Comment by natronics** [comment]
I also can't install.

I think it might be a problem with vagrant and rubygems:

https://bugs.launchpad.net/ubuntu/+source/vagrant/+bug/1562696

**Comment by kusnier** [comment]
As @natronics mentioned it this belongs to the bug above. I will close this for cleanup
