### ISSUE TITLE
Destroying a vm with no persistent storage attached fails with stacktrace

### ISSUE THREAD

**Issue by vStone** [kusnier/vagrant-persistent-storage#62]
I added the plugin with a vm already booted up and destroying it resulted in:

```
/home/user/.vagrant.d/gems/2.2.5/gems/vagrant-persistent-storage-0.0.24/lib/vagrant-persistent-storage/providers/virtualbox/driver/base.rb:68:in `realpath': No such file or directory @ realpath_rec - /path/to/vagrant-data.vdi (Errno::ENOENT)
	from /home/user/.vagrant.d/gems/2.2.5/gems/vagrant-persistent-storage-0.0.24/lib/vagrant-persistent-storage/providers/virtualbox/driver/base.rb:68:in `realpath'
	from /home/user/.vagrant.d/gems/2.2.5/gems/vagrant-persistent-storage-0.0.24/lib/vagrant-persistent-storage/providers/virtualbox/driver/base.rb:68:in `identical_files'
	from /home/user/.vagrant.d/gems/2.2.5/gems/vagrant-persistent-storage-0.0.24/lib/vagrant-persistent-storage/providers/virtualbox/driver/base.rb:60:in `block in read_persistent_storage'
	from /home/user/.vagrant.d/gems/2.2.5/gems/vagrant-persistent-storage-0.0.24/lib/vagrant-persistent-storage/providers/virtualbox/driver/base.rb:56:in `each'
	from /home/user/.vagrant.d/gems/2.2.5/gems/vagrant-persistent-storage-0.0.24/lib/vagrant-persistent-storage/providers/virtualbox/driver/base.rb:56:in `read_persistent_storage'
	from /home/user/.vagrant.d/gems/2.2.5/gems/vagrant-persistent-storage-0.0.24/lib/vagrant-persistent-storage/providers/virtualbox/driver/base.rb:44:in `detach_storage'
	from /home/user/.vagrant.d/gems/2.2.5/gems/vagrant-persistent-storage-0.0.24/lib/vagrant-persistent-storage/action/detach_storage.rb:25:in `call'
```

**Comment by kusnier** [comment]
Commit 0db4436fd4d8827c7db4b0cc0f810a19814dfc2c will fix this issue

**Comment by kusnier** [comment]
Version 0.0.26 released. close #62
